# Generated by Django 5.1.1 on 2024-10-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_karly_cash_customuser_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='karly_cash',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mileage',
        ),
    ]
