# Generated by Django 5.1.1 on 2024-10-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_karly_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='karly_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
