# Generated by Django 5.1.1 on 2024-10-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_orderview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderView',
        ),
    ]
