# Generated by Django 5.1.1 on 2024-10-21 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
