# Generated by Django 5.1.1 on 2024-10-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_referred_by_customuser_referrer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referrer',
        ),
    ]
