# Generated by Django 5.1.2 on 2024-10-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_orderview'),
        ('users', '0012_remove_customuser_referral_code_and_more'),
    ]

    operations = [
    ]
