# Generated by Django 5.1.2 on 2024-10-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_deactivated_at_customuser_is_deactivated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deactivated',
        ),
    ]
