# Generated by Django 5.1.2 on 2024-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
