# Generated by Django 5.1.2 on 2024-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_is_password_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_password_set',
            new_name='is_social',
        ),
    ]
