# Generated by Django 5.1.2 on 2024-10-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_rename_created_order_order_date'),
        ('reviews', '0006_blockedreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.orderitem'),
        ),
    ]
