# Generated by Django 5.1.1 on 2024-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_allergy_info_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='Notice_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(default='포장 타입 입력', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='판매자 입력', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_info',
            field=models.CharField(default='배송 정보 입력', max_length=200),
        ),
    ]
