# Generated by Django 5.1.1 on 2024-10-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderView',
        ),
    ]
